
-- 1. Enable RLS (Row Level Security) untuk semua tabel yang ada
alter table "public"."santri" enable row level security;
alter table "public"."musammi" enable row level security;
alter table "public"."halaqah" enable row level security;
alter table "public"."halaqah_santri" enable row level security;
alter table "public"."attendance" enable row level security;
alter table "public"."informasi" enable row level security;

-- 2. Buat Tabel Chat
create table if not exists "public"."chat" (
    "id" bigint generated by default as identity not null primary key,
    "created_at" timestamp with time zone default now() not null,
    "content" text not null,
    "sender_email" text not null,
    "is_deleted" boolean default false not null
);

-- 3. Enable RLS untuk Chat
alter table "public"."chat" enable row level security;

-- 4. Membuat Policies (Aturan Keamanan)
create policy "Enable read access for all users" on "public"."chat" as permissive for select to public using (true);
create policy "Enable insert for authenticated users only" on "public"."chat" as permissive for insert to authenticated with check (true);
-- Hanya pemilik pesan (berdasarkan email) yang boleh menghapus pesannya sendiri
create policy "Enable delete for message owner" on "public"."chat" as permissive for delete to authenticated using ((auth.jwt() ->> 'email') = sender_email);

-- !!! PENTING !!!
-- 5. AKTIFKAN REALTIME REPLICATION UNTUK TABEL CHAT
-- Tanpa perintah ini, pesan tidak akan muncul otomatis di user lain!
alter publication supabase_realtime add table "public"."chat";

-- =========================================================
-- UPDATE: PENAMBAHAN KODE UNIK (ID KHUSUS) AGAR TIDAK TERTUKAR
-- =========================================================

-- 1. Tambah kolom 'kode' di tabel santri dan musammi
alter table "public"."santri" add column if not exists "kode" text;
alter table "public"."musammi" add column if not exists "kode" text;

-- 2. Tambahkan constraint unique agar kode tidak boleh kembar
alter table "public"."santri" drop constraint if exists "santri_kode_key";
alter table "public"."santri" add constraint "santri_kode_key" unique ("kode");

alter table "public"."musammi" drop constraint if exists "musammi_kode_key";
alter table "public"."musammi" add constraint "musammi_kode_key" unique ("kode");

-- 3. (Opsional) Generate kode otomatis untuk data lama yang masih kosong
update "public"."santri" set kode = 'S-' || lpad(id::text, 4, '0') where kode is null;
update "public"."musammi" set kode = 'M-' || lpad(id::text, 4, '0') where kode is null;

-- =========================================================
-- UPDATE BARU: TABEL WALI KELAS
-- =========================================================

create table if not exists "public"."wali_kelas" (
    "id" bigint generated by default as identity not null primary key,
    "created_at" timestamp with time zone default now() not null,
    "nama" text not null,
    "marhalah" text not null,
    "kelas" text not null,
    "no_hp" text
);

alter table "public"."wali_kelas" enable row level security;

create policy "Enable all access for authenticated users (Wali Kelas)" on "public"."wali_kelas" 
    for all to authenticated using (true) with check (true);
